### ISSUE TITLE
embeddings

### ISSUE THREAD

**Issue by wh1t3tea** [Hazqeel09/ellzaf_ml#1]
I have problems with using GhostFaceNetsV2 as feature extractor. As I see it doesn't provide 512 vector if use num_classes=None.
![image](https://github.com/Hazqeel09/ellzaf_ml/assets/128380279/f18573aa-c48f-4ed5-9a0b-5007e05bbe74)
![image](https://github.com/Hazqeel09/ellzaf_ml/assets/128380279/ef1d2bd0-f361-409c-ab58-b7be0e622e82)
Can you help me with that?

**Comment by Hazqeel09** [comment]
Have you tried with num_classes=0 instead?

**Comment by khursani8** [comment]
I don't think related to num_classes
this model embeddings is 8192
if you want before classifier embeddings can add below code, and do any pooling technique you prefer
```
model.classifier = nn.Identity()
```

which will output 960 and not 512

**Comment by khursani8** [comment]
https://colab.research.google.com/drive/1mWQiNdiaI41PI3YTNIAfeewQJd3Zsw7U?usp=sharing
![image](https://github.com/Hazqeel09/ellzaf_ml/assets/5404903/6409f711-8e9b-4d07-91f5-3e6afedfa003)

**Comment by Hazqeel09** [comment]
Thank you @khursani8. @wh1t3tea please confirm if his method fix your problem

**Comment by wh1t3tea** [comment]
Yeah, it works fine, but i have a question about .mean(-1), is it correct to squeeze dims like that? I'm begginer and see this for the first time.

**Comment by khursani8** [comment]
> Yeah, it works fine, but i have a question about .mean(-1), is it correct to squeeze dims like that? I'm begginer and see this for the first time.
> 
> 

Yes and No, 
Reason for squeeze like that because it not pretrained weight and just random weight, so just for example only
Usually people use pooling https://www.kaggle.com/code/debarshichanda/pytorch-arcface-gem-pooling-starter

Or can read more on retrieval paper

https://amaarora.github.io/posts/2020-08-30-gempool.html

**Comment by wh1t3tea** [comment]
Thanks a lot! now it looks reasonable for me

**Comment by Hazqeel09** [comment]
@wh1t3tea i have reread the paper and go through the paper code again. i've fixed the implementation and will release it in the next 12 hours

**Comment by wh1t3tea** [comment]
@Hazqeel09, It's would be great! haven't found any other pytorch implementations of this model, so you are doing great job. Thanks!

**Comment by wh1t3tea** [comment]
Now it works good
![image](https://github.com/Hazqeel09/ellzaf_ml/assets/128380279/c55e42bc-45c7-4b99-a2e7-6444b70a27dd)

**Comment by khursani8** [comment]
Ohh sorry @wh1t3tea , i did not read the paper and assume the implementation correct. Since I usually use embeddings before classifier

**Comment by Hazqeel09** [comment]
it's okay @khursani8, the mistake was on my side. at that time, i'm still trying to do these implementations sksksk

thank you for trying to help and joining the discussion

**Comment by Hazqeel09** [comment]
@wh1t3tea i've released 1.4.7 to fix the implementation, kindly try the latest version
